[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    miguelbalboa/MFRC522@^1.4.10
    h2zero/NimBLE-Arduino@^1.4.0
    https://github.com/softplus/GoogleFormPost.git
    WiFi
monitor_speed = 115200
board_build.filesystem = spiffs
